FROM python:3.10

WORKDIR /app

COPY . /app/credit_scoring_project


RUN pip install --upgrade pip
RUN pip install -r credit_scoring_project/requirements.txt

ENV PYTHONPATH=/app

WORKDIR /app/credit_scoring_project

RUN ls -la output

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]